### ISSUE TITLE
Applescript Error

### ISSUE THREAD

**Issue by carbon43** [emorydunn/CaptureOneScripts#2]
Running 10.15.5, and getting an Applescript error when I run the make_new_dir script (havent tried others yet). Error attached for reference. It is entirely possible this is an issue on my end, as I tend to do quite a bit of weird and wonderful poking at the OS level, so happy to explore this further/collect more information if helpful. FWIW it does actually create the directory, however it does not set it as the capture dir.

![Screen Shot 2020-08-24 at 5 14 15 AM](https://user-images.githubusercontent.com/30049486/91026732-262ea600-e5c9-11ea-831d-d44fd21dc1aa.png)

**Comment by emorydunn** [comment]
Good catch, I'm not sure how I missed that one. I've fixed the issue, so if you download the script again you'll be all set.

**Comment by carbon43** [comment]
Wow, that is the fastest Ive ever had someone respond and fix anything on Github 😳Just tested, works perfect. Thank you!!

**Comment by emorydunn** [comment]
Luckily it was an easy fix, I just had to add a single word 😄
